name: AWS RDS Proxy IAM Database Connect

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IDENTITY_POSTGRES_PASSWORD: "default"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn

      - name: Save VPN Config
        run: echo "${{ secrets.STG_VPN_CONFIG }}" >> /tmp/config.ovpn

      - name: start VPN
        run: sudo openvpn --config /tmp/config.ovpn --log "/var/log/vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 2
        run: until ping -c1 ${{secrets.STG_JUMP_IP}}; do sleep 2; done

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql -y

      - name: Connect to PostgreSQL
        run: |
          export RDSHOST="stg-v2-primary-db-proxy-iam-2.proxy-ce9bljj6mci9.us-east-1.rds.amazonaws.com"
          export PGPASSWORD="$(aws rds generate-db-auth-token --hostname $RDSHOST --port 5432 --region us-east-1 --username stg-identity-user )"
          wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
          psql "host=$RDSHOST port=5432 dbname=identitydb user=stg-identity-user password=$PGPASSWORD" sslrootcert=global-bundle.pem -c "SELECT * FROM  pg_catalog.pg_tables "
          echo $RDSHOST
           
      - name: Set Environment Variables
        env:
          IDENTITY_POSTGRES_PASSWORD: $PGPASSWORD
          
      - name: Test
        run: |
         echo ${{env.IDENTITY_POSTGRES_PASSWORD}}
         echo $IDENTITY_POSTGRES_PASSWORD
        
